### ISSUE TITLE
Algunas correcciones en la documentación

### ISSUE THREAD

**Issue by cgosorio** [Alvaro9rc/TFG-Web-Analisis-Sintactico#15]
En la portada en vez de:
```tex
  \begin{center}%
  {%
    \noindent\LARGE
    Presentado por \@author{}\\ 
    en Universidad de Burgos --- \@date{}\\
    Tutor: \@tutor{}\\
    Tutor: Alvar Arnaiz Gonzalez
  }%
  \end{center}%
```

Usa mejor:
```tex
  \begin{center}%
  {%
    \noindent\LARGE
    Presentado por \@author{}\\ 
    en Universidad de Burgos --- \@date{}\\
    \begin{tabbing}
    Tutores: \= \kill
    Tutores: \> Dr. \@tutor{}\\
             \> Dr. Álvar Arnaiz González
    \end{tabbing}
  }%
  \end{center}%
```

También, siempre que uses «python 2» o «python 3», utiliza mejor «Python 2» o «Python 3», dado que deberían tener la consideración de nombres propios.

**Comment by alvarag** [comment]
Algunos comentarios sobre los pdf

[anexosAAG.pdf](https://github.com/Alvaro9rc/TFG-Web-Analisis-Sintactico/files/8415699/anexosAAG.pdf)

[memoriaAAG.pdf](https://github.com/Alvaro9rc/TFG-Web-Analisis-Sintactico/files/8415698/memoriaAAG.pdf)
