### ISSUE TITLE
Hay que añadir el método __eq__ a la clase Set

### ISSUE THREAD

**Issue by cgosorio** [Alvaro9rc/TFG-Web-Analisis-Sintactico#7]
Después de unas «pocas» horas investigando el problema, ¡he descubierto el problema que había en el código!

A pesar de que la herramienta `2to3` dice que no hay nada que cambiar en `osets.py`, sí es necesario un cambio. En Python2 el predicado `in` para comprobar la pertenencia de un elemento en una lista usaba el método `__cmp__`, pero en Python3 el método que se usa es el `__eq__` y éste no estaba definido en `osets.py`, con lo que se quedaba en un bucle infinito en el método `TRAVERSE` de la clase `CFGrammar`, porque no paraban de añadirse elementos a una lista donde en realidad ya estaban.

La solución para este problema (ahora se ven otros, que tendrías que corregir) es simplemente añadir este método en la clase `Set` en `osets.py`:
```Python
    def __eq__(self, other):
        return self.members == other.members
````
Para más información sobre este problema, puedes leer este: https://stackoverflow.com/questions/8276983/why-cant-i-use-the-method-cmp-in-python-3-as-for-python-2, creo que está relacionado con el hecho de que hayas tenido que definir la función `compare` en `parser.py`.

**Comment by Alvaro9rc** [comment]
Arreglado. Muchas gracias!

**Comment by cgosorio** [comment]
Me he dado cuenta de que esa implementación de `__eq__` es demasiado ingenua, utiliza mejor esta otra que es más robusta:

```python
def __eq__(self, other):
    if isinstance(other, list):
        return set(self.members) == set(other)
    elif isinstance(other, Set):
        return set(self.members) == set(other.members)
    else:
        raise TypeError("Incompatible type for Set comparison")
```

Por algún lado me ha dado errores porque hay comparaciones entre osets y listas, con esa implementación de `__eq__` eso se puede hacer sin problemas.

**Comment by Alvaro9rc** [comment]
Hecho.
